### ISSUE TITLE
JuliaPackaging logo

### ISSUE THREAD

**Issue by ararslan** [JuliaPackaging/Roadmap.jl#1]
I made a logo for the organization, which we can use if people like it. 😄

![julia box](https://cloud.githubusercontent.com/assets/6396159/16530289/42797940-3f7c-11e6-9f47-70b15fc62808.png)

(migrated here from JuliaPackaging/cloneallpackages#2, which predates the creation of this repo and my membership in the org)

**Comment by tkelman** [comment]
go for it

**Comment by ararslan** [comment]
Status: Completed.

**Comment by ararslan** [comment]
Btw, thanks for adding me to the organization @tkelman. Kind of unexpected but I appreciate it! Looking forward to helping out.
