### ISSUE TITLE
Homebrew packages

### ISSUE THREAD

**Issue by ararslan** [JuliaPackaging/Roadmap.jl#2]
I've been working on a Homebrew formula for OpenLibm and it kinda sorta works but could use some work and isn't really production ready. Currently it lives in https://github.com/ararslan/homebrew-pints. Is this something that JuliaPackaging would like to adopt? I know a certain @staticfloat is a Homebrew expert...

**Comment by tkelman** [comment]
I think this would go in https://github.com/staticfloat/homebrew-julia (which I guess we could move here?), I'm not sure why that isn't using openlibm as a separate formula

**Comment by ararslan** [comment]
Having Elliot's Julia Homebrew stuff here seems like a good idea to me, but I guess I don't know the exact motivation behind this organization. What will this organization primarily be used for?

**Comment by ararslan** [comment]
I guess I assumed it'd be for building distribution packages for things like Homebrew, APT, etc.

**Comment by tkelman** [comment]
Not necessarily, but wouldn't hurt to have that centralized either. I was more thinking generic package manager related things, potentially even moving metadata, compat, or others to separate the CI queues. @timholy had mentioned this idea under the name "JuliaPackages" on a mailing list thread a while back, I just decided to modify the name a little.

**Comment by ararslan** [comment]
Oh okay, I remember seeing that on the mailing list. I guess the change of "packages" to "packaging" is what threw me off. 😜

I actually think centralizing the Homebrew/APT/.deb/whatever stuff would be a good idea but if this is more for Julia packages rather than packaging Julia then I guess that would be out of scope here.

**Comment by tkelman** [comment]
We could do both I suppose, though I haven't been too invested in distro packaging of Julia myself. Usually we leave that to individual contributors to maintain. Having them in one place might at least make it easier to share notes.

**Comment by staticfloat** [comment]
@ararslan if you want to create a separate openlibm formula, I have no objections.  Feel free to open a pull request or issues for specific problems you have.  :)
